### PR TITLE
Fixing docs folder setup.

### PR DESCRIPTION
**Pull request by homotechsual**
When including documentation (.md) files from outside the docs folder includes don't work. Instead we need to rely on trusty symlinks. 

The documentation for docs-publisher will be updated to clarify this.

### CODE REVIEW

**Comment by homotechsual** [comment]
@alifrumin worked out why it wasn't working - found a weird edge case where includes don't work properly. Will clarify in docs-publisher documentation.

**Comment by alifrumin** [comment]
@MikeyMJCO I appreciate you taking time to look at this.  The diff looks like it deletes a line and then adds the same line back, can you explain to me how this fixes things?

Screenshot_2019-05-21 Fixing docs folder setup by MikeyMJCO · Pull Request #6 · aghstrategies com aghstrategies tsys

**Comment by homotechsual** [comment]
What it's actually doing is removing the file and adding a symlink - GitHub unhelpfully shows symlinks as the path to the actual file.

**New File:**

https://github.com/aghstrategies/com.aghstrategies.tsys/blob/302f3c2fe4873ed35cf1b9354d3f8f9c20ba3a89/docs/index.md

(See at the top it says Symbolic Link)

**Old File:**

https://github.com/aghstrategies/com.aghstrategies.tsys/blob/dbb9901c49a0d1dd113a50f5baaab8be8c6b2a9c/docs/index.md

(We have a line count here because it's an actual file)

**Comment by alifrumin** [comment]
ok, got it great

**Comment by alifrumin** [comment]
Thanks again @MikeyMJCO

**Comment by homotechsual** [comment]
Voila :-)

https://docs.civicrm.org/tsys/en/latest/

**Comment by alifrumin** [comment]
Awesome I will update the info.xml

**Comment by homotechsual** [comment]
You've also got a "Documentation" section in the readme which links to GitHub - that could be removed?

**Comment by alifrumin** [comment]
I will fix that up too this is great thanks

**Pull request merged**
