### PR TITLE
Upgrade civix (and bump min-req 5.65)

### PR DESCRIPTION
**Pull request by mlutfy**
Bumping the minimum-requirements avoids mixins (and < 5.65 is ancient).

Updating civix is required for Smarty5 compat.

### CODE REVIEW

**Comment by mlutfy** [comment]
hi @alifrumin, can you review this PR? It causes issues with latest versions of CiviCRM.

**Comment by alifrumin** [comment]
Hi @mlutfy I will look at this next week.

**Comment by alifrumin** [comment]
Thanks @mlutfy

**Comment by mlutfy** [comment]
Thanks @alifrumin !

**Pull request merged**
